### ISSUE TITLE
XML to JSON

### ISSUE THREAD

**Issue by ebebbington** [ebebbington/data-format-converter#1]

**Comment by michael-spengler** [comment]
I tried it for some minutes using https://github.com/nashwaan/xml-js as a template - did not succeed so far.

You might consider funding this issue via https://gitcoin.co with some 0.something Ether.

**Comment by michael-spengler** [comment]
another potential template: https://github.com/buglabs/node-xml2json/blob/master/lib/xml2json.js

**Comment by michael-spengler** [comment]
this one seems to come closest to a simple solution: https://deno.land/x/serializexml@v0.3.2#alternatively-build-tags-by-passing-an-object

with this I can imagine one "just" needs to bring any json to the expected object structure see link.

**Comment by ebebbington** [comment]
Hey @michael-spengler, sorry i didn't realise you commented on this issue, my bad!

**Comment by ebebbington** [comment]
> this one seems to come closest to a simple solution: https://deno.land/x/serializexml@v0.3.2#alternatively-build-tags-by-passing-an-object
> 
> with this I can imagine one "just" needs to bring any json to the expected object structure see link.

that would work for json to xml, but not for xml to json right?

**Comment by ebebbington** [comment]
I'm 90% of the way there - if anyone can supply any complex XML they have it would help checking my implementation works properly

**Comment by ebebbington** [comment]
Still can't crack it, and i've probably spent over half a dozen hours on it now, at least. Going to wait until some 3rd party (or Deno DOMParser) service is available
