### ISSUE TITLE
XML to JSON is not working if the data is too large

### ISSUE THREAD

**Issue by shanilsasikumar** [ebebbington/data-format-converter#17]
When I try to convert the XML data to JSON, the following error is generated.

`thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(TooLong)'`

I have used the following method to convert the XML to JSON

```
const xmlResponse= await fetch(
        `xmlURLPath`,
        {
          method: "GET",
        },
      );
const xmlData= await xmlResponse.text();
const result = XMLtoJSON(xmlData);
```

I have given my `xmlURLPath` directly to the XMLtoJSON function, it's working only for the public URL, not for the localhost path.

**Comment by ebebbington** [comment]
Thanks @shanilsasikumar, i'll look into this week, and apologies for any inconvenience

**Comment by ebebbington** [comment]
@shanilsasikumar can you provide the xml you used? and also the code and and the stack trace?

**Comment by shanilsasikumar** [comment]
> @shanilsasikumar can you provide the xml you used? and also the code and and the stack trace?

This is the error that I got when I try to convert XML data to JSON from a local URL (http://localhost:3100/sample.xml)

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (deno:op_crates/fetch/26_fetch.js:866:19)
    at async Module.XMLtoJSON (xml_to_json.ts:42:49)
    at async robots_sitemap_test.ts:50:25
    at async asyncOpSanitizer (deno:cli/rt/40_testing.js:36:7)
    at async Object.resourceSanitizer [as fn] (deno:cli/rt/40_testing.js:70:7)
    at async TestRunner.[Symbol.asyncIterator] (deno:cli/rt/40_testing.js:245:13)
    at async Object.runTests (deno:cli/rt/40_testing.js:322:22)
    at async $deno$test.ts:17:1
```
But when the sample.xml is available in a publically accessible URL it is working fine.

**Comment by ebebbington** [comment]
Thanks, can you provide the contents of `sample.xml`? I assume you have a server listening on`localhost:3000/:filename`, and your route/resource will do something like:

```typescript
public GET () {
  const filename = this.request.pathParam("filename")
  const data = Deno.readFileSync(filename)
  const json = XMLtoJSON(data)
}
```
?

**Comment by ebebbington** [comment]
@shanilsasikumar

**Comment by LucasLpr** [comment]
You can try to parse [this link](https://boardgamegeek.com/xmlapi2/thing?id=13&versions=1&stats=1). Same error here thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(TooLong)'

**Comment by ebebbington** [comment]
> You can try to parse [this link](https://boardgamegeek.com/xmlapi2/thing?id=13&versions=1&stats=1). Same error here thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(TooLong)'

Thanks, will look into it 👍

**Comment by ebebbington** [comment]
Hi @LucasLpr, i've decided to remove this repo. Whilst you will get an email about this comment, you wont be able to view this repo. Please see htts://deno.land/x/data_format_converter@v1.2.1

Ultimately, I use an API to do the conversion, which isn't a great way to implement it
